### PR TITLE
Fix speed test label overlap

### LINKED ISSUE #430: Speed test gui average labels overlap on similar values
If average latencies are same or very close to each other the labels added to the chart overlap:

image

Reported by @pekkakortelainen

### PR DESCRIPTION
**Pull request by Wiljami**
Speed test labels used to go over each other when the latency averages were too close to each other.

Now the lower value's label is underneath the line.

Worst case scenario where the labels would have been right over each other looks like following now:
image

Closes #430

### CODE REVIEW

File: js/sitestatus.js [hunk 1]
```diff
@@ -132,9 +132,9 @@ jQuery(document).ready(function($) {
       },
       tooltip: {
           y: {
-              formatter: function(val) {
-                  return val + " ms"
-              }
+          formatter: function(val) {
+              return val + " ms"
+            }
```
Comment (elguitar) [inline js/sitestatus.js:137]: Indentation seems to have gone wrong

**Comment by elguitar** [comment]
I don't have time to test this in production. Could you @nellileinonen test and review?

**Comment by nellileinonen** [comment]
Works and looks good!
