### PR TITLE
Fix optimize images input validation

### LINKED ISSUE #415: Optimize images does not validate width and height properly
You can add text behind the width and height options in 'Optimze images' and it saves the values.

When you refresh the page, the values with letters behind them are still there.

optimize images

### PR DESCRIPTION
**Pull request by Wiljami**
It was possible to put values such as '100asd' as width and height.
Now the values are checked to make sure they're proper numbers.

Seems php has interesting ways of comparing values. 1000 < '2000asdf' returns true even when the other is a string and with extra non-number characters!

Closes #415

### CODE REVIEW

File: modules/sitestatus.php [hunk 1]
```diff
@@ -526,31 +526,35 @@ public static function optimize_images_settings_description() {
...
-          'invalid-width',
-          sprintf(
-            // translators: %s numeric value for the minimum image width
-            __('The minimum width for image optimisation is %1$s px. Setting suggested width of %2$s px.', 'seravo'),
-            self::$min_width,
-            self::$max_width_default
-          )
-        );
-        return self::$max_width_default;
+      if ( get_option('seravo-enable-optimize-images') === 'on' && $width !== null ) {
```
Comment (Wiljami) [inline modules/sitestatus.php:529]: I cut this if line to two to make it clearer what's going on.

File: modules/sitestatus.php [hunk 2]
```diff
@@ -526,31 +526,35 @@ public static function optimize_images_settings_description() {
...
     public static function sanitize_image_height( $height ) {
-      if ( $height < self::$min_height && $height !== null && get_option('seravo-enable-optimize-images') === 'on' ) {
-        add_settings_error(
-          'seravo-image-max-resolution-height',
-          'invalid-height',
-          // translators: %s numeric value for the minimum image height
-          sprintf(__('The minimum height for image optimisation is %1$s px. Setting suggested height of %2$s px.', 'seravo'), self::$min_height, self::$max_height_default)
-        );
-        return self::$max_height_default;
+      if ( get_option('seravo-enable-optimize-images') === 'on' && $height !== null ) {
```
Comment (Wiljami) [inline modules/sitestatus.php:548]: I cut this if line to two to make it clearer what's going on.

File: modules/sitestatus.php [hunk 3]
```diff
@@ -262,7 +262,7 @@ public static function seravo_disk_usage() {
         <?php
           $api_response = API::get_site_data();
           if ( is_wp_error($api_response) ) {
-            die($api_response->get_error_message());
+          die($api_response->get_error_message());
```
Comment (elguitar) [inline modules/sitestatus.php:265]: This indentation is wrong
